export const POST_MDB_CONFIG = 'POST_MDB_CONFIG';
export const POST_MOVIE_POPULAR = 'POST_MOVIE_POPULAR';
export const POST_TV_POPULAR = 'POST_TV_POPULAR';
export const SET_ITEM_TYPE_TV = 'SET_ITEM_TYPE_TV';
export const SET_ITEM_TYPE_MOVIE = 'SET_ITEM_TYPE_MOVIE';